### ISSUE TITLE
int、long、float、double数值类型字段查询数据报类型转换的错

### ISSUE THREAD

**Issue by ihongyang** [Spatio-Temporal-Lab/start-db-achive#285]
示例SQL
create table t_int (int1 int);
create table t_integer (int2 integer);
create table t_long (long3 long);
create table t_float (float4 float);
create table t_double (double5 double);
insert into t_int values (123);
insert into t_integer values (123);
insert into t_long values (1234567890);
insert into t_float values (123.456);
insert into t_double values (123456.789);
select * from t_int;
select * from t_integer;
select * from t_long;
select * from t_float;
select * from t_double;

![image](https://user-images.githubusercontent.com/104311524/176495807-e7a8c109-5f6d-4c1c-bb9a-8a9ffd340147.png)

**Comment by jimolonely** [comment]
@ihongyang 可以复测了

**Comment by ihongyang** [comment]
复测通过
![image](https://user-images.githubusercontent.com/104311524/177186185-20d7495e-5d98-447e-940d-b2c741fdb2aa.png)
